// Galaxy phones to add to index seed file

{
    name: 'Galaxy', 
    generation: 'S23 Ultra', 
    release_yr: '2023',
    price: [1199.99, 1379.99, 1619.99],
    storage: ['256GB', '512GB', '1TB'],
    screen_size: '6.8"',
    cx_rating: '4.8',
    connector_type: 'USB-C',
    camera_qual: '200MP',
    ext_storage: false,
    platform_id: platforms[0]._id,
    make_id: makes[0]._id, 
    image: `https://image-us.samsung.com/us/smartphones/galaxy-s23-ultra/images/gallery/lavender/01-DM3-Lavender-PDP-1600x1200.jpg?$product-details-jpg$`,
},
{
    name: 'Galaxy', 
    generation: 'S23+', 
    release_yr: '2023',
    price: [999.99, 1119.99],
    storage: ['256GB', '512GB'],
    screen_size: '6.6"',
    cx_rating: '4.7',
    connector_type: 'USB-C',
    camera_qual: '50MP',
    ext_storage: false,
    platform_id: platforms[0]._id,
    make_id: makes[0]._id, 
    image: `https://image-us.samsung.com/us/smartphones/galaxy-s23/images/gallery/cream/dm2/01-DM2-Cream-PDP-1600x1200.jpg?$product-details-jpg$`,
},
{
    name: 'Galaxy', 
    generation: 'Z Fold4', 
    release_yr: '2023',
    price: [1799.99, 1919.99, 2159.99],
    storage: ['256GB', '512GB', '1TB'],
    screen_size: '7.6"',
    cx_rating: '4.7',
    connector_type: 'USB-C',
    camera_qual: '50MP',
    ext_storage: false,
    platform_id: platforms[0]._id,
    make_id: makes[0]._id, 
    image: `https://image-us.samsung.com/us/smartphones/galaxy-z-fold4/gallery-images/08042022/Gallery-Q4-Green-01-1600x1200.jpg?$product-details-jpg$`,
},
{
    name: 'Galaxy', 
    generation: 'A54 5G', 
    release_yr: '2023',
    price: [449.99],
    storage: ['128GB', '256GB'],
    screen_size: '6.4"',
    cx_rating: '4.7',
    connector_type: 'USB-C',
    camera_qual: '50MP',
    ext_storage: true,
    platform_id: platforms[0]._id,
    make_id: makes[0]._id, 
    image: `https://image-us.samsung.com/SamsungUS/configurator/A54-01-black-Configurator-DT-800x600.jpg`,
},